### ISSUE TITLE
[bug] Output rss.xml is not ordered by pubDate

### ISSUE THREAD

**Issue by LeslieLeung** [halo-dev/plugin-feed#26]
输出的RSS没有按照时间排序，见 https://ameow.xyz/rss.xml 。

可能是以下这个地方使用了 map 导致丢失了顺序。
https://github.com/halo-dev/plugin-feed/blob/0c648ca49e7415a2d19d565b9f095d6e439b4061/src/main/java/run/halo/feed/FeedServiceImpl.java#L154C14-L154C21

**Comment by JohnNiang** [comment]
Hi @LeslieLeung , thanks for reaching out here.

这里确实错误地使用了 flatMap 导致最终排序不稳定，如果换成 concatMap 应该可以解决问题。如果 @LeslieLeung 有兴趣的话， 非常欢迎提交 PR 修复这个问题。

https://github.com/halo-dev/plugin-feed/blob/0c648ca49e7415a2d19d565b9f095d6e439b4061/src/main/java/run/halo/feed/FeedServiceImpl.java#L154

/good-first-issue
