### ISSUE TITLE
【功能增强】希望rss.xml中能够增加内容主体

### ISSUE THREAD

**Issue by z-hanzhe** [halo-dev/plugin-feed#27]
现在的rss仅包含 description 描述信息，希望能够将文章内容加进 content:encoded，这样也方便其他系统通过 rss 快速同步

**Comment by ruibaby** [comment]
<img width="653" alt="image" src="https://github.com/halo-dev/plugin-feed/assets/21301288/3af2a77b-a946-4f48-a48f-3d06663dcb7d">

**Comment by z-hanzhe** [comment]
原来插件还有单独的设置，之前没留意....
