### ISSUE TITLE
rss 可以在作者主页展示订阅图标

### ISSUE THREAD

**Issue by QYG2297248353** [halo-dev/plugin-feed#35]
作者主页地址
https://{domain}/authors/{user_id}

但是没有配置的地方

![image](https://github.com/user-attachments/assets/2753ecfd-99e3-4ca5-87a7-a94ccaae5e94)

我不太确定应该是找主题仓库反馈，还是在插件仓库反馈

**Comment by ruibaby** [comment]
插件无法控制，这种需求建议自己改主题。

/close
