### ISSUE TITLE
希望适配follow，增加一些选项

### ISSUE THREAD

**Issue by verkyer** [halo-dev/plugin-feed#36]
follow是比较火的rss，目前使用它订阅halo，有一下几个情况：

## 默认情况下
![Image](https://github.com/user-attachments/assets/5ad68e04-2f06-4e8e-a0df-dc8af3585831)
![Image](https://github.com/user-attachments/assets/2e9e0db9-b855-4c2e-bcf2-8c9875a798e7)

---

## 全文模式
![Image](https://github.com/user-attachments/assets/9cabba16-6ed0-4fa5-998b-cdb53d963e07)
![Image](https://github.com/user-attachments/assets/82abc1bf-33e2-454b-8054-dc26ffe7b4d2)

### 1、小众软件
![Image](https://github.com/user-attachments/assets/3d62db97-c12d-499d-af68-c4884e2260ed)
https://www.appinn.com/feed/
体验就很不错

### 2、异次元软件
![Image](https://github.com/user-attachments/assets/01a19878-41df-4161-b541-e8b771402ac0)
https://feed.iplaysoft.com/
这个就是RSS只有摘要，但是提供了个【查看原文】的按钮；觉得也是不错的思路。

以上仅供参考，也希望RSS插件能增强一些功能

**Comment by guqing** [comment]
已经在 https://github.com/halo-dev/plugin-feed/pull/39 中完善了 feed 插件，等待下个版本发布

关于查看原文一般 RSS 阅读器都会有跳转功能，比如点击标题，或者如 follow 在右上角有一个链接图标
