### ISSUE TITLE
支持创建不同的 Rss Feed 仅包括指定标签的文章

### ISSUE THREAD

**Issue by HowieHz** [halo-dev/plugin-feed#38]
支持创建不同的 Rss Feed 仅包括指定标签的文章

**Comment by HowieHz** [comment]
@JohnNiang

**Comment by guqing** [comment]
我的理解是你期望能实现一个根据标签订阅文章的功能 `/feed/tags/{tagName}.xml`

/kind feature

**Comment by HowieHz** [comment]
> 我的理解是你期望能实现一个根据标签订阅文章的功能 `/feed/tags/{tagName}.xml`
> 
> /kind feature

是这样的
