### ISSUE TITLE
RSS插件最近状态：Ready	FALSE	StartError	Failed to parse configuration class [run.halo.feed.provider.PostRssProvider]

### ISSUE THREAD

**Issue by WangZaiOY** [halo-dev/plugin-feed#53]
装上这个插件似乎启动不了，没有生成rss.xml和feed.xml文件，插件状态显示：
`

类型 | 状态 | 原因 | 信息 | 时间
-- | -- | -- | -- | --
Ready | FALSE | StartError | Failed to parse configuration class [run.halo.feed.provider.PostRssProvider] | 几秒前
Initialized | TRUE | Loaded | - | 几秒前

`
应该怎么解决啊

**Comment by guqing** [comment]
Halo 和 feed 插件分别是什么版本呢

**Comment by WangZaiOY** [comment]
> Halo 和 feed 插件分别是什么版本呢

谢谢大佬，一语道破梦中人，是我粗心了没看到最新的1.4.1版本要halo2.20.11以上才行，我的halo是2.20.7的，没想到halo社区的制作团队这么活跃，迭代这么快

**Comment by ruibaby** [comment]
> > Halo 和 feed 插件分别是什么版本呢
> 
> 谢谢大佬，一语道破梦中人，是我粗心了没看到最新的1.4.1版本要halo2.20.11以上才行，我的halo是2.20.7的，没想到halo社区的制作团队这么活跃，迭代这么快

1.4 版本的 requires 是 >=2.20.11，理论上低于这个版本号是安装不上 1.4 版本的插件的，这是怎么安装上的呢🤔
