### ISSUE TITLE
插件在 2.4 版本中无法正常使用

### ISSUE THREAD

**Issue by LIlGG** [halo-dev/plugin-feed#9]
### Halo 版本
2.4.1

### 插件版本
v1.1.0-beta.1

### 描述信息
插件主题端访问报错，并会打印出 SQL 查询语句。

![image](https://user-images.githubusercontent.com/31335418/229674865-4e6a5b33-1e1f-4039-af93-3a64511fc84c.png)

### 日志信息

[halo-log-2023-04-04 10_43.log](https://github.com/halo-sigs/plugin-feed/files/11144161/halo-log-2023-04-04.10_43.log)

**Comment by ruibaby** [comment]
这个问题在 https://github.com/halo-dev/plugin-feed/commit/89f3e78a57ccc30dedaf2371b769695c64c08124 中已修复。

/close
